### ISSUE TITLE
커뮤니티 리스트 모달 두 번클릭 버그 수정완료

### ISSUE THREAD

**Issue by cpk0709** [Hanghae-Final-6-8/Hanghae-Final-6-8-FrontEnd#51]
커뮤니티 리스트에서 게시물 우측 상단 ... 버튼 두 번 클릭해야했던 버그 수정하였습니다.

원인 : PostList.tsx 에 모달을 토글 해줄 state가 있고, modalToggle.ts 컴포넌트 내에서도 토글 해줄 state가 있어서, 이중으로 토글 state를 관리해야하는 상황이었습니다. 이 두 개의 state가 서로 따로따로 놀아서 두 번을 클릭해야하는 버그가 생겼습니다.

해결 : toggle을 관리하는 리덕스를 하나 만들어서 전역상태를 관리하게하여 두 개의 컴포넌트가 하나의 state를 관리할 수 있게 하였습니다.

문제: toggle하나 관리하겠다고 리덕스를 새로 만든것이 비효율적인지 의문이 듭니다. 기존의 posts리덕스에 모달 토글용 state를 추가하려했으나, 이미 posts리덕스는 코드가 충분히 지저분해서 추가하지 않았습니다. 더 나은 아이디어가 있으시면 알려주시기바랍니다!

**Comment by JuhwanLeeKR** [comment]
해당 issue는 #43  이슈의 해결법이 맞을까요?
맞다면 앞으로는 해당 이슈에 comment로 추가하는게 좀 더 좋아보입니다.

저도 기존 모달창은 useState로 임시 관리를 하였으나,
사용성이 복잡하게 될 경우 redux로 모달 상태관리를 따로 하는게 좋은 걸로 알고 있습니다!
