### ISSUE TITLE
커뮤니티 부분 파일업로드 확장자명 제한 해야할거 같습니다.

### ISSUE THREAD

**Issue by JuhwanLeeKR** [Hanghae-Final-6-8/Hanghae-Final-6-8-FrontEnd#52]
파일 선택 창에서 동영상 파일을 눌러도 확인이 되더라구요

확장자 예외처리를 해놔야할거같습니다.

해결되면 코멘트와함께 close issue 하시면 됩니다.

**Comment by cpk0709** [comment]
동영상파일 안보이도록 확장자 설정 하였습니다.
