### ISSUE TITLE
커뮤니티 부분 UX를 향상 시키기 위한 피드백

### ISSUE THREAD

**Issue by JuhwanLeeKR** [Hanghae-Final-6-8/Hanghae-Final-6-8-FrontEnd#58]
커뮤니티 기능은 대부분 동작하는거 같으나
댓글 입력시 엔터로 가능하게,
게시물 작성시 요건을 충족하지 못하면 빨간색 알림창이 나오고
사용자가 다시 입력을 시작하면 경고창이 사라지게 하는 보완이 필요해 보입니다.

**Comment by cpk0709** [comment]
react-hook-form 적용을 해서 일단 엔터치면 동작은 할것입니다. 경고창은 게시물 제목과 내용은 작성하면 사라지는데, 태그와 이미지선택은 사라지지않아서 이부분 수정해보겠습니다.

**Comment by cpk0709** [comment]
유저가 정상적으로 값 입력하면 경고문구 사라지게하였습니다. #58
