### ISSUE TITLE
내활동부분 버그

### ISSUE THREAD

**Issue by JuhwanLeeKR** [Hanghae-Final-6-8/Hanghae-Final-6-8-FrontEnd#59]
현재 마이페이지에서 내 활동이 제대로 로드가 안되고 있습니다.
정확한 이해를 위해 하단 이미지를 참고 바랍니다.
<img width="310" alt="COPICK - 나만의 원두로 시작하는 일상 - Chrome 22-05-27 (금) 오전 11_04_13" src="https://user-images.githubusercontent.com/87694150/170614294-df4cee72-f819-473d-9a92-1320bfbb8b1c.png">
<img width="316" alt="COPICK - 나만의 원두로 시작하는 일상 - Chrome 22-05-27 (금) 오전 11_04_25" src="https://user-images.githubusercontent.com/87694150/170614301-9ad6772b-e9f1-479f-9900-2bf7005f87f9.png">
<img width="324" alt="COPICK - 나만의 원두로 시작하는 일상 - Chrome 22-05-27 (금) 오전 11_04_28" src="https://user-images.githubusercontent.com/87694150/170614303-4bdb2472-7d9b-4486-a86c-d6788490fa86.png">

**Comment by cpk0709** [comment]
동현님 서버 api response값에 맞춰서 불러와지기가 안되는거같습니다. 새로 업데이트하면 해결되지않을까싶습니다

**Comment by cpk0709** [comment]
해당 버그 해결되었습니다. #59
